apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-volume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps-deployment-volume
  template:
    metadata:
      labels:
        app: apps-deployment-volume
    spec:
      containers: 
      - name: hello-world
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args: ["echo '--- Контейнер запущен ---'; while true; do cat /etc/greeting/message; echo ''; sleep 5; done"]
        volumeMounts: 
        - name: greeting-volume
          mountPath: /etc/greeting
      volumes:
      - name: greeting-volume
        configMap:
          name: hello-configmap
