apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: curlimages/curl:latest
            command: ["/bin/sh", "-c"]
            args: ["date"]
          restartPolicy: OnFailure