apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template: 
    spec: 
      containers:
      - name: job-container
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"] 
        args: ["curl -s http://example.com"] 
      restartPolicy: OnFailure
  backoffLimit: 4
