apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: "POD-1"
    last-update-by: "pupupuup@gmail.com"
  name: nginx-1
  namespace: nginx-1
  labels:
    app: nginx-1
spec:
  containers:
  - name: nginx-1
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: "POD-2"
    last-update-by: "pupupuup@gmail.com"
  namespace: nginx-2
  name: nginx-2
  labels:
    app: nginx-2
spec:
  containers:
  - name: nginx-2
    image: nginx:latest
    ports:
    - containerPort: 80